name: Clippy

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust -> target"

      - name: Add Clippy Component
        working-directory: rust
        run: rustup component add clippy

      - name: Clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --locked -- -Dwarnings
          filter_mode: nofilter
          fail_on_error: true
